name = "nnjl"
uuid = "1b7f3ed1-fccf-43d2-86f1-538f92492255"
authors = ["offlinebot <flintstonelg@gmail.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
JSON = "0.21.4"
